name: Deploy

# clare all permissions for GITHUB_TOKEN
permissions: {}

on:
  workflow_call:
    inputs:
      maven-version:
        description: 'The Maven version used during build job'
        required: false
        default: '3.9.9'
        type: string

      jdk-version:
        description: 'jdk version for build'
        required: false
        default: '21'
        type: string

      jdk-distribution:
        description: 'jdk distribution for build'
        required: false
        default: 'temurin'
        type: string

      branch-to-deploy:
        description: 'Git branch name'
        required: false
        default: 'refs/heads/master'
        type: string

# allow single build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy

    if: |
      github.event_name == 'push' && 
      github.repository_owner == 'codehaus-plexus' && 
      github.ref == inputs.branch-to-deploy &&
      !startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare release')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.jdk-version }}
          distribution: ${{ inputs.jdk-distribution }}
          cache: 'maven'
          server-id: sonatype-central-portal
          server-username: MAVEN_DEPLOY_UID
          server-password: MAVEN_DEPLOY_PWD

      - name: Set up Maven
        run: mvn --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper "-Dtype=only-script" "-Dmaven=${{ inputs.maven-version }}"

      - name: Publish Snapshot
        run: echo "deploy skipped temporally"
#        run: ./mvnw -e -B -V deploy -DskipTests
        env:
          MAVEN_DEPLOY_UID: ${{ secrets.MAVEN_DEPLOY_UID }}
          MAVEN_DEPLOY_PWD: ${{ secrets.MAVEN_DEPLOY_PWD }}
